//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public struct Point
{
	public int X;
	public int Y;

	public Point(int X, int Y)
	{
		this.X = X;
		this.Y = Y;
	}

	public bool equals(Point other)
	{
		if ((X == other.X) && (Y == other.Y))
			return true;
		return false;
	}
}

public class PathNode
{
	// Координаты точки на карте.
	public Point Position { get; set; }
	// Длина пути от старта (G).
	public int PathLengthFromStart { get; set; }
	// Точка, из которой пришли в эту точку.
	public PathNode CameFrom { get; set; }
	// Примерное расстояние до цели (H).
	public int HeuristicEstimatePathLength { get; set; }
	// Ожидаемое полное расстояние до цели (F).
	public int EstimateFullPathLength {
		get {
			return this.PathLengthFromStart + this.HeuristicEstimatePathLength;
		}
	}
}


